import streamlit as st
from fpdf import FPDF
from datetime import datetime
from io import BytesIO
import os
import uuid

def show_generated_contrat():
    st.set_page_config(page_title="Contract Generator - ChainVestor Hub", layout="wide")
        
    # === SIDEBAR ===
    st.sidebar.title("📚 Contract Options")
    st.sidebar.info("Generate a certified document confirming that the recommendations came from ChainVestor Hub.")
    if st.sidebar.button("⬅️ Return to Assistant"):
        st.session_state.page = "main"
        st.rerun()

    st.title("📄 ChainVestor Official Investment Confirmation")
    st.markdown("""
    This document confirms that the information and recommendation(s) you received were generated by our AI-powered assistant based on uploaded documents and due diligence rules.
    """)

    # Pré-remplir la dernière réponse
    last_answer = ""
    if "history" in st.session_state:
        for msg in reversed(st.session_state.history):
            if msg["role"] == "assistant":
                last_answer = msg["content"]
                break

    with st.form("contract_form"):
        col1, col2 = st.columns(2)
        with col1:
            name = st.text_input("👤 Full Name")
            email = st.text_input("📧 Email Address")
            validator = st.text_input("✅ Validated by (Compliance Expert)")
        with col2:
            session_id = st.text_input("🗂️ Session ID", value=st.session_state.get("session_name", ""))
            contract_reason = st.text_area("📌 Reason for Confirmation (e.g. Investment Approved, Due Diligence Passed)", height=80)
            contract_id = str(uuid.uuid4()).split("-")[0].upper()

        st.subheader("🧠 Summary of Recommendation")
        summary = st.text_area("🧠 AI-Generated Answer", value=last_answer, height=160)

        submitted = st.form_submit_button("✅ Generate Certified Contract")

    if submitted:
        if not all([name, email, session_id, summary, validator, contract_reason]):
            st.warning("⚠️ All fields are required.")
            return

        pdf = FPDF()
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=15)

        logo_path = "assets/chainvestor_logo.png"
        if os.path.exists(logo_path):
            pdf.image(logo_path, x=10, y=8, w=40)

        pdf.set_font("Arial", 'B', 16)
        pdf.cell(0, 15, "ChainVestor Hub – Official Due Diligence Certificate", ln=True, align='C')
        pdf.ln(5)

        # Info utilisateur
        pdf.set_font("Arial", '', 12)
        pdf.multi_cell(0, 10, f"""
🧾 CONTRACT ID: {contract_id}
📅 Date Issued: {datetime.today().strftime('%Y-%m-%d %H:%M:%S')}

👤 Name: {name}
📧 Email: {email}
🗂️ Session ID: {session_id}
👨‍⚖️ Validated By: {validator}

📌 Contract Purpose:
{contract_reason}

📜 Summary of ChainVestor Assistant Recommendation:
""")

        pdf.set_font("Arial", 'I', 12)
        pdf.multi_cell(0, 10, f"\"{summary.strip()}\"")
        pdf.set_font("Arial", '', 12)

        pdf.ln(5)
        pdf.multi_cell(0, 10, """
✅ We confirm that all information above was generated through ChainVestor Hub's AI-powered due diligence assistant and reflects the platform’s analysis based on uploaded and verified documents.

⚠️ This contract is system-generated and digitally certified by our compliance service. It should not be altered manually.

""")

        # Signature area
        pdf.ln(10)
        pdf.cell(0, 10, "Signed by:", ln=True)
        pdf.cell(0, 10, "ChainVestor Hub Compliance Bot", ln=True)
        pdf.cell(0, 10, "Signature: ____________________________", ln=True)
        pdf.cell(0, 10, "Date: _________________________________", ln=True)

        pdf_bytes = pdf.output(dest='S').encode('latin-1')
        st.success("✅ Contract successfully generated.")
        st.download_button(
            label="📥 Download Certified Contract PDF",
            data=BytesIO(pdf_bytes),
            file_name=f"{session_id}_confirmation_{contract_id}.pdf",
            mime="application/pdf"
        )

        # Optionnel : journal MongoDB si besoin
        db["contracts"].insert_one({
           "contract_id": contract_id,
           "user_email": email,
           "name": name,
            "validator": validator,
             "summary": summary,
            "reason": contract_reason,
             "timestamp": datetime.utcnow()
        })

